### ISSUE TITLE
Tidy up Camunda Platform Helm notes

### ISSUE THREAD

**Issue by aabouzaid** [DevOpsHiveNet/devops-coding-mentorship#3]
The Camunda Platform Helm notes could be better.

By doing this task, you will gain the following skills:
- Basic Helm chart development.

### The Challange

Camunda Platform Helm chart has multiple components (applications), and some users don't need all components, so if one of the components is disabled, it should not show in the Helm notes.

### The Task

You need to add conditions in the `Connecting to Web apps` section, so if one of the apps is disabled, it should not appear in the notes.

Also you need to add the Ingress host if it's enabled (it's not mentioned in the notes at all).

### Notes

The Helm chart note [is not rendered](https://github.com/helm/helm/issues/6901) via the `helm template [...]` command; you need to find a different way to debug it.

### Links
- [ ] Add Ingress details into NOTES.txt  - https://github.com/camunda/camunda-platform-helm/issues/736

**Comment by mustafaabdulluh** [comment]
Hi @aabouzaid , Okay, I am interested in this, I know Helm a little bit, but I didn't use this camunda before, should I know something before contributing to it? I don't understand the issue.

**Comment by aabouzaid** [comment]
@mstva I've updated the task, is it clear now?

**Comment by mustafaabdulluh** [comment]
@aabouzaid Okay, I understand the task now, I will see how to fix it after setup this repo locally, I have some questions:
- I see that someone has fixed it and it was merged but you opened it again, could I know why? is the solution that he provided not working?
- you said that "you need to find a different way to debug it" if you are fixing it yourself, what you will do with this? I need some hints

**Comment by mustafaabdulluh** [comment]
@aabouzaid I found [this](https://helm.sh/docs/chart_template_guide/notes_files/) and I think it is the way I could use it to debug, what do you think?

**Comment by mustafaabdulluh** [comment]
I added something like this for the ingress issue, what do you think?
```
- Ingress:
  - Enabled: {{ .Values.global.ingress.enabled }}
  {{- if .Values.global.ingress.enabled }}
  - Ingress Host: {{ .Values.global.ingress.host }}
  {{- end }}
```

I can't find those Ingress URLs that you are talking about in the issue

Also for the `Connecting to Web apps` issue, I see that there are conditions that actually do what you ask about, I don't understand your problem.

**Comment by aabouzaid** [comment]
@mstva let's have a call to give you a better summary.
Send me a message on LinkedIn or Facebook.

**Comment by mustafaabdulluh** [comment]
@aabouzaid Okay, I sent you an invitation on Linkedin

**Comment by mustafaabdulluh** [comment]
@aabouzaid I opened a PR

**Comment by aabouzaid** [comment]
@mustafaelghrib FYI, I'm on vacation till the beginning of July, and I will review it once I'm back.

**Comment by aabouzaid** [comment]
@mustafaelghrib merged, great job 👏 👏 

If you like the Helm topic, there are more advanced tasks 😁

**Comment by mustafaabdulluh** [comment]
Hi @aabouzaid Yes it would be great!
Is that will be related to Camunda as well?
I see some other issues, I could work on them if that the case. What do you think?
